
theme:  minima
title:  a test bolg
author: tongliangfa
email: tongliangfa@hongdefund.com

description: > # this means to ignore newlines until "baseurl:"
   an awesome description for my new site here.
   It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle
github_username:  tongliangfa

show_excerpts: true # set to false to remove excerpts on the homepage
